### ISSUE TITLE
Haiti: Grafana email plugin needs to accept dates in different formats in report file name (deliverable 19)

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/msupply-dashboard-app#103]
## Please describe the feature being requested.
Haiti need dates to be included in reports automatically emailed from the Grafana dashboard.

## Agreed solution
Modify the Grafana emailing plugin needs to enable setting of the date format to be used and position in the report name. 

Date formats and positions in filename required (example filenames shown):
1. Daily_Warehouse_Stock_Inventory_DD-MM-YYYY.xlsx - 2-digit day number and month number, 4 digit year all separated by hyphens.
2. Goods receipt-MMM YYYY.xlsx - 3 character month (Jan, Feb, Mar, Apr etc.) and 4 digit year separated by a space.
3. Both these date formats are shown at the end fo the filename. If possible, allow beginning or end of filename as a selection.

### Describe alternatives you've considered

This is what they asked for.

### Moneyworks Jobcode 
HAI:CONV

**Comment by sworup** [comment]
Merged with 7b31c75
