### ISSUE TITLE
datasource id changes

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-dashboard-app#36]
Whenever the grafana server changes the postgres datasource ID increments.

I.e. it is set to 10 - reset server, goes to 11.

Ugh.

Could do something like using the default datasource, probably?

**Comment by mark-prins** [comment]
this is my fault, I think. 
There's a line in the provisioning script which deletes and recreates the datasource - removing that will fix the problem :)

**Comment by mark-prins** [comment]
been working ok after removing.
