### ISSUE TITLE
Backup SQLite

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-dashboard-app#38]
Some thing something Ujwal and backup SQLite

**Comment by mark-prins** [comment]
The file `C:\Program Files\mSupply Dashboard\data\msupply.db` should be added to the backup schedule, as documented in the [dashboard wiki](https://sussol.net/wiki/doku.php/projects:dashboard:grafana:backups)

**Comment by mark-prins** [comment]
configured on the demo-board server and a note made in the documentation to refer to this issue.
