### ISSUE TITLE
Right align numbers in spreadsheet

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/msupply-dashboard-app#39]
When populating data in the sheet, determine if a value is numeric. If it is, right align it.

Perhaps have this as a configuration option too?

**Comment by joshxg** [comment]
Whoops forgot this one! For reference: https://github.com/openmsupply/msupply-dashboard-app/blob/3be1553b62d81261c244cf932d0bda979406e466/backend/pkg/reporter/reporter.go#L121-L122

With this package: https://xuri.me/excelize/en/cell.html#SetCellDefault

I suppose just using the `SetStringCell` and `SetIntCell` funcs, although that doesn't solve it for floats, so possibly having to use `SetCellStyle`. 


Hm!

**Comment by mark-prins** [comment]
Closed by #40
