### ISSUE TITLE
Excel formatting

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/msupply-dashboard-app#49]
A request to improve the formatting of the spreadsheet

- column widths should be relevant to content
- dates should be formatted as dates

other suggestions? @joshxg @craigdrown

**Comment by craigdrown** [comment]
Well thank you for asking!
Right-align numbers. 
The end.

**Comment by mark-prins** [comment]
Excellent! Right align was picked up by @joshxg in #39

**Comment by mark-prins** [comment]
closed with #52
