### ISSUE TITLE
App Configuration page does not validate even with valid data

### ISSUE THREAD

**Issue by sworup** [openmsupply/msupply-dashboard-app#73]
## Details

After the fix to https://github.com/openmsupply/msupply-dashboard-app/issues/71, when we try to add configuration to Plugin, the validation fails.

![Screen Shot 2022-02-24 at 6 08 51 PM](https://user-images.githubusercontent.com/683452/155523518-6138d193-384f-431e-93c9-f215ea6f4078.jpg)

**Comment by joshxg** [comment]
Hi @sworup 

Thanks a lot for looking into it!

I'm not sure why this is occurring, but my guess is:


-The name in `register` differs from the `input` name? https://github.com/openmsupply/msupply-dashboard-app/blob/3be59cd164d659ef04dddb78a80ce2b07d4fe07f/frontend/src/components/Settings/ConfigurationForm.tsx#L53-L56

and some info:

- This component is using a form library from `@grafana/ui`, that is actually `react-hook-form` https://react-hook-form.com/ 
- It's been awhile, but I believe the easiest way for you to debug would be to pull the `grafana` repo and point the plugins folder to this repo on your machine, or put the repo into the grafana plugins directory. You shouldn't need the `msupply-dashboard` repo and I believe you won't need any datasources properly setup, to get started at least.

```
// custom.ini
[paths]
plugins = "/Users/joshuagriffin/repos/grafana-plugins" 
```

**Comment by sworup** [comment]
@joshxg I did notice the difference in react hook form registry name and tried to fix before I moved out but with no luck. I will try again tomorrow.
