### ISSUE TITLE
Email report : Lookback period does not work

### ISSUE THREAD

**Issue by Mai21** [openmsupply/msupply-dashboard-app#76]
In the email report, Lookback period does not work even though there are records on the actual dashboard panel.

![Screen Shot 2022-03-03 at 4 56 19 PM](https://user-images.githubusercontent.com/36495540/156494959-88e685ae-cea8-4f3c-bf08-b47e95f91aa2.png)

<img width="1408" alt="Screen Shot 2022-03-03 at 5 11 57 PM" src="https://user-images.githubusercontent.com/36495540/156495066-00226b74-fc15-4973-ad20-f980591b06b0.png">

**Comment by Mai21** [comment]
I guess that these `schedule.Interval` in `reportEmailer.go` would be `content.Lookback` from ReportContent?

https://github.com/openmsupply/msupply-dashboard-app/blob/3be59cd164d659ef04dddb78a80ce2b07d4fe07f/backend/pkg/reportEmailer/reportEmailer.go#L114-L116

https://github.com/openmsupply/msupply-dashboard-app/blob/3be59cd164d659ef04dddb78a80ce2b07d4fe07f/backend/pkg/reportEmailer/reportEmailer.go#L238-L240

Because `schedule.Interval` is an integer for setting time intervals. 
https://github.com/openmsupply/msupply-dashboard-app/blob/3be59cd164d659ef04dddb78a80ce2b07d4fe07f/backend/pkg/dbstore/schedule.go#L60-L88

**Comment by sworup** [comment]
@Mai21 I will look into this and get back to you.

**Comment by sworup** [comment]
@Mai21 changing the interval to lookback did not work by itself, I am investigating further.

**Comment by sworup** [comment]
Upon investigating I come to this conclusion

- https://www.getpostman.com/collections/6db526c90f4a08a3b0d0

- Grafana query expects epoch timestamp or relative text in from and to. However, during my test, I found that epoch timestamp does not work, I had made sure that I put the correct epoch in. Relative time like `now` or `now-5m` still works. 
- The query works with hardcoded time too.
- So this seems to be a Grafana ds api issue too, while your suggested lookback variable change was also important.
- I will try to make the epoch timestamp work with grafana. You can play with above postman collection, change variables to see how it work.

---

Notice the query works but the rows are blank

![Screen Shot 2022-06-21 at 12 07 03 PM](https://user-images.githubusercontent.com/683452/174730177-39034dd9-3ce3-45a6-9252-ce39381e6e8d.jpg)

---
This works. So does hardcoded time.
![Screen Shot 2022-06-21 at 12 08 06 PM](https://user-images.githubusercontent.com/683452/174730364-9ca19058-faba-4d4d-9f2c-c9b8ae2d1ee1.jpg)

**Comment by sworup** [comment]
Just did some testing and found that grafana expects epoch timestamp in microseconds, while the date conversion in our code at least is converting in seconds. Now epoch timestamp system could be seconds, miliseconds or microseonds but `$__timeTo()` method does not do the check and expect the time to be milliseconds hence putting in the oldest 1970s date time... this ends up getting blank values.

I think if we convert the timestamp to milliseconds before sending we should be good. Postman test are yielding results.

**Comment by sworup** [comment]
> Because `schedule.Interval` is an integer for setting time intervals. 
> https://github.com/openmsupply/msupply-dashboard-app/blob/3be59cd164d659ef04dddb78a80ce2b07d4fe07f/backend/pkg/dbstore/schedule.go#L60-L88

@Mai21 this instance decides when to generate report and is using  `schedule.Interval` correctly.

**Comment by sworup** [comment]
@Mai21 6151d15 checked into https://github.com/openmsupply/msupply-dashboard-app/pull/82 fixes this issue. Please check.

**Comment by Mai21** [comment]
@sworup Thanks for the investigation! That's a good catch about the difference between microseconds and seconds. I'll test them!

**Comment by Mai21** [comment]
I tested with the latest branch, but it seems something wrong...
It looks lookback does not save properly... 
![Screen Shot 2022-06-22 at 3 55 16 PM](https://user-images.githubusercontent.com/36495540/174947945-9e01e2e6-8ab4-44dc-9850-2c8fd8d4a420.png)
<img width="701" alt="Screen Shot 2022-06-22 at 3 55 10 PM" src="https://user-images.githubusercontent.com/36495540/174948002-96037beb-ab41-4eed-8e42-73687a28bc8a.png">

When I saved the value with the first screenshot, the database is like the second screenshot. 
I calculated them simply like below.
Current date : 05:11:00 22th June 2022
|  current date | lookback in database | current date - lookback |  date after lookback |
| ---- | ---| ---| ---|
| 1655874660 | 86400000 | 1569474660 | 05:11:00 26th Sep 2019 |
| 1655874660 | 172800000 | 1483074660 | 05:11:00 30th Dec 2016 |
| 1655874660 | 14515200000 | -12859325340 | Error |
| 1655874660 | 1209600000 | 446274660 | 05:11:00 22th Feb 1984 |

Also, even if the lookback date is wrong like above, the first line should work because the result would be between 2019-09-26 and 2022-06-22 and there are records in the database. But currently no data is retrieved in the report I received by email.

In postgres log, when I set 4 weeks lookback, the value going to be minus and caught the error below.

> /*timeFilter*/ select * from item_line where expiry_date BETWEEN '-175542-04-25T06:53:20Z' AND '54442-07-03T06:53:20Z'

So it looks the current date-time is also wrong...?

**Comment by sworup** [comment]
I will look into this @Mai21. Thanks for testing the issue.
